use crate::{
    types::Result,
    traits::DatabaseInterface,
    btc_on_eth::{
        check_core_is_initialized::check_core_is_initialized_and_return_eth_state,
        eth::{
            eth_state::EthState,
            validate_block::validate_block_in_state,
            get_eth_output_json::get_eth_output_json,
            validate_receipts::validate_receipts_in_state,
            save_btc_utxos_to_db::maybe_save_btc_utxos_to_db,
            filter_receipts::filter_irrelevant_receipts_from_state,
            check_parent_exists::check_for_parent_of_block_in_state,
            filter_redeem_params::maybe_filter_redeem_params_in_state,
            create_btc_transactions::maybe_create_btc_txs_and_add_to_state,
            parse_redeem_params::maybe_parse_redeem_params_and_add_to_state,
            update_eth_linker_hash::maybe_update_eth_linker_hash_and_return_state,
            increment_btc_nonce::maybe_increment_btc_nonce_in_db_and_return_state,
            extract_utxos_from_btc_txs::maybe_extract_btc_utxo_from_btc_tx_in_state,
            update_latest_block_hash::maybe_update_latest_block_hash_and_return_state,
            remove_old_eth_tail_block::maybe_remove_old_eth_tail_block_and_return_state,
            parse_eth_block_and_receipts::parse_eth_block_and_receipts_and_put_in_state,
            update_eth_tail_block_hash::maybe_update_eth_tail_block_hash_and_return_state,
            update_eth_canon_block_hash::maybe_update_eth_canon_block_hash_and_return_state,
            add_block_and_receipts_to_database::maybe_add_block_and_receipts_to_db_and_return_state,
            remove_receipts_from_canon_block::maybe_remove_receipts_from_canon_block_and_return_state,
            eth_database_transactions::{
                end_eth_db_transaction_and_return_state,
                start_eth_db_transaction_and_return_state,
            },
        },
    },
};

pub fn submit_eth_block_to_enclave<D: DatabaseInterface>(db: D, block_json_string: &str) -> Result<String> {
    info!("✔ Submitting ETH block to enclave...");
    parse_eth_block_and_receipts_and_put_in_state(block_json_string, EthState::init(db))
        .and_then(check_core_is_initialized_and_return_eth_state)
        .and_then(start_eth_db_transaction_and_return_state)
        .and_then(validate_block_in_state)
        .and_then(check_for_parent_of_block_in_state)
        .and_then(validate_receipts_in_state)
        .and_then(filter_irrelevant_receipts_from_state)
        .and_then(maybe_add_block_and_receipts_to_db_and_return_state)
        .and_then(maybe_update_latest_block_hash_and_return_state)
        .and_then(maybe_update_eth_canon_block_hash_and_return_state)
        .and_then(maybe_update_eth_tail_block_hash_and_return_state)
        .and_then(maybe_update_eth_linker_hash_and_return_state)
        .and_then(maybe_parse_redeem_params_and_add_to_state)
        .and_then(maybe_filter_redeem_params_in_state)
        .and_then(maybe_create_btc_txs_and_add_to_state)
        .and_then(maybe_increment_btc_nonce_in_db_and_return_state)
        .and_then(maybe_extract_btc_utxo_from_btc_tx_in_state)
        .and_then(maybe_save_btc_utxos_to_db)
        .and_then(maybe_remove_old_eth_tail_block_and_return_state)
        .and_then(maybe_remove_receipts_from_canon_block_and_return_state)
        .and_then(end_eth_db_transaction_and_return_state)
        .and_then(get_eth_output_json)
}
